service: random-number
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  timeout: 10
  memorySize: 128
  logRetentionInDays: 7
  tracing:
    lambda: true
    apiGateway: true
  environment:
    STAGE: ${sls:stage}
    AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
    APPCONFIG_APPLICATION_ID:
      Ref: AppConfigApplication
    APPCONFIG_ENVIRONMENT_ID:
      Ref: AppConfigEnvironment
    APPCONFIG_CONFIGURATION_PROFILE_ID:
      Ref: AppConfigConfigurationProfile
  layers:
    - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-7-0:1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - appconfig:GetLatestConfiguration
            - appconfig:StartConfigurationSession
          Resource: "*"
        - Effect: Allow
          Action:
            - codedeploy:*
          Resource:
            - "*"

package:
  individually: true

functions:
  get-random-number:
    handler: src/handlers/random-number/index.handler
    events:
      - http:
          path: random/number
          method: get
    deploymentSettings:
      type: AllAtOnce
      alias: Live

resources:
  - ${file(./sls/appconfig.yml)}

plugins:
  - serverless-esbuild
  - serverless-prune-plugin # for removing old lambda versions
  - serverless-offline
  - serverless-plugin-canary-deployments

custom:
  esbuild:
    minify: false
    bundle: true
    sourcemap: true

  prune:
    automatic: true
    number: 5
