Resources:
  AppConfigApplication:
    Type: AWS::AppConfig::Application
    Properties:
      Name: ${self:service}-${sls:stage}
      Description: Random Number generator

  AppConfigEnvironment:
    Type: AWS::AppConfig::Environment
    Properties:
      Name: ${sls:stage}
      Description: Dev environment for Random Number
      ApplicationId: !Ref AppConfigApplication

  AppConfigConfigurationProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      ApplicationId: !Ref AppConfigApplication
      Name: ${self:service}-${sls:stage}
      Description: Configuration profile for random number
      LocationUri: hosted
      Type: AWS.AppConfig.FeatureFlags

  AppConfigHostedConfigurationVersion:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId: !Ref AppConfigApplication
      ConfigurationProfileId: !Ref AppConfigConfigurationProfile
      Description: 'Feature flags for random number'
      # You can retrieve the configuration from an existing feature flag you created manually by running
      # aws appconfig get-hosted-configuration-version --application-id upp1jmh --configuration-profile-id 9rlgfs6 --version-number 3 test.json
      # cat test.json
      Content: !Sub ${file(sls/enableLambda.js):generate}
      ContentType: 'application/json'

  AppConfigDeploymentStrategyAllAtOnce:
    Type: AWS::AppConfig::DeploymentStrategy
    Properties:
      Name: AllAtOnce
      Description: Deployment strategy used for immediate swapping of configuration
      DeploymentDurationInMinutes: 0
      FinalBakeTimeInMinutes: 0
      GrowthFactor: 100
      GrowthType: LINEAR
      ReplicateTo: NONE

  AppConfigDeployment:
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId: !Ref AppConfigApplication
      ConfigurationProfileId: !Ref AppConfigConfigurationProfile
      ConfigurationVersion: !Ref AppConfigHostedConfigurationVersion
      DeploymentStrategyId: !Ref AppConfigDeploymentStrategyAllAtOnce
      EnvironmentId: !Ref AppConfigEnvironment
