name: publish-tag

on:
  push:
    tags:
      - '*'

jobs:
  build-affected:
    name: Core build, lint and test
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 16
      tooling-cache: yarn
      stage: prd
      target-build: true
      target-lint: true
      target-unit-tests: true
      target-get-environment-url: false

  publish-affected:
    runs-on: ubuntu-latest
    needs: [ build-affected ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn
      - run: make build
        working-directory: ./
      - run: make publish-npm
        working-directory: ./
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
